"""Who Am I? — character pool (dark, absurd, political, literal bulbs)."""

CHARACTERS = [
    "A light bulb",
    "A flickering fluorescent tube",
    "Thomas Edison",
    "Adolf Hitler",
    "Joseph Stalin",
    "Benito Mussolini",
    "Winston Churchill",
    "Margaret Thatcher",
    "Donald Trump",
    "Joe Biden",
    "Vladimir Putin",
    "Napoleon Bonaparte",
    "Cleopatra",
    "Fidel Castro",
    "Kim Jong-un",
    "Queen Elizabeth II",
    "Karl Marx",
    "Ronald Reagan",
    "Emmanuel Macron",
    "Mahatma Gandhi",
    "The Pope",
    "Oscar the Grouch",
    "Henry VIII",
    "Marie Antoinette",
    "Genghis Khan",
    "Julius Caesar",
    "Alexander the Great",
    "Joan of Arc",
    "Nikola Tesla",
    "Elon Musk",
    "Boris Johnson",
    "Theresa May",
    "Rishi Sunak",
    "Xi Jinping",
    "Mao Zedong",
    "Pol Pot",
    "Idi Amin",
    "Robert Mugabe",
    "Silvio Berlusconi",
    "Nero",
    "Caligula",
    "A Roman candle",
    "A lava lamp",
    "A disco ball",
    "A haunted Victorian lamp",
    "A conspiracy theorist",
    "A tax auditor",
    "Your ex",
    "A passive-aggressive Post-it note",
    "A LinkedIn thought leader",
    "A haunted Roomba",
    "The British weather",
    "A hung parliament",
    "A coalition government",
    "A filibuster",
    "A red telephone",
    "A nuclear football",
    "A UN peacekeeper",
    "A lobbyist",
    "A focus group",
]
