"""Spectrum prompt pairs for Dial — server-authoritative."""

SPECTRA: list[tuple[str, str]] = [
    ("Cold", "Hot"),
    ("Underrated", "Overrated"),
    ("Useless", "Useful"),
    ("Scary", "Not scary"),
    ("Cheap", "Expensive"),
    ("Round", "Pointy"),
    ("Fantasy", "Sci-fi"),
    ("Bad superpower", "Good superpower"),
    ("Forbidden", "Encouraged"),
    ("Common", "Rare"),
    ("Unhealthy", "Healthy"),
    ("Casual", "Formal"),
    ("Quiet", "Loud"),
    ("Old", "New"),
    ("Weird", "Normal"),
    ("Boring", "Exciting"),
    ("Temporary", "Permanent"),
    ("Introvert", "Extrovert"),
    ("Guilty pleasure", "Universally loved"),
    ("Hard to do", "Easy to do"),
    ("Smells bad", "Smells good"),
    ("A want", "A need"),
    ("Overrated food", "Underrated food"),
    ("Villain", "Hero"),
    ("Ugly", "Beautiful"),
    ("Cringe", "Cool"),
    ("Waste of money", "Worth it"),
    ("Childish", "Grown-up"),
    ("Calm", "Chaotic"),
    ("A chore", "A treat"),
    ("Forgettable", "Iconic"),
    ("Slow", "Fast"),
    ("Messy", "Tidy"),
    ("Cursed", "Blessed"),
    ("Basic", "Fancy"),
    ("Overshare", "Keep to yourself"),
    ("Soft", "Hard"),
    ("Dry", "Wet"),
    ("Light", "Heavy"),
    ("Tame", "Wild"),
    ("Quiet night in", "Big night out"),
    ("Low effort", "High effort"),
    ("A myth", "Real"),
    ("Awkward", "Smooth"),
]
