"""initial schema

Revision ID: add0bdb6c9a7
Revises: 
Create Date: 2026-08-13 19:35:34.073037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add0bdb6c9a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverstory_custom_packs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverstory_player_profiles',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('preferred_timer_secs', sa.Integer(), nullable=False),
    sa.Column('preferred_pack_ids', sa.JSON(), nullable=False),
    sa.Column('preferred_custom_pack_ids', sa.JSON(), nullable=False),
    sa.Column('preferred_spy_count', sa.Integer(), nullable=False),
    sa.Column('preferred_view_mode', sa.String(), nullable=False),
    sa.Column('recent_rooms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('coverstory_playtest_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_size', sa.Integer(), nullable=False),
    sa.Column('timer_secs', sa.Integer(), nullable=False),
    sa.Column('pack_ids', sa.JSON(), nullable=False),
    sa.Column('completed_rounds', sa.Integer(), nullable=False),
    sa.Column('rejoin_issues', sa.Boolean(), nullable=False),
    sa.Column('confusing_locations', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverstory_rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_code', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('timer_secs', sa.Integer(), nullable=False),
    sa.Column('spy_count', sa.Integer(), nullable=False),
    sa.Column('pack_ids', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverstory_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverstory_rounds_room_code'), ['room_code'], unique=False)

    op.create_table('fixtures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('after_extra_time', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('leagues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('organiser_hash', sa.String(), nullable=True),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pro_status', sa.String(), nullable=False),
    sa.Column('pro_purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leagues_code'), ['code'], unique=True)

    op.create_table('admin_overrides',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_league_id'), ['league_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('initials', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_league_id'), ['league_id'], unique=False)

    op.create_table('funnel_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funnel_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funnel_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_funnel_events_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_funnel_events_session_id'), ['session_id'], unique=False)

    op.create_table('league_purchases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_checkout_session_id')
    )
    with op.batch_alter_table('league_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_purchases_league_id'), ['league_id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('initials', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('lt_member', sa.Boolean(), nullable=False),
    sa.Column('leadership', sa.Boolean(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('is_oi', sa.Boolean(), nullable=False),
    sa.Column('is_organiser', sa.Boolean(), nullable=False),
    sa.Column('picks', sa.JSON(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('pred_score', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_league_id'), ['league_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_checkout_session_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_participant_id'), ['participant_id'], unique=False)

    op.create_table('profile_assets',
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    with op.batch_alter_table('profile_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_assets_league_id'), ['league_id'], unique=False)

    op.create_table('profiles',
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('favourite_team', sa.String(), nullable=False),
    sa.Column('avatar_source', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('avatar_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_google_id'), ['google_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_league_id'), ['league_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_league_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_google_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('profile_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_assets_league_id'))

    op.drop_table('profile_assets')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_participant_id'))
        batch_op.drop_index(batch_op.f('ix_payments_league_id'))

    op.drop_table('payments')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_league_id'))

    op.drop_table('participants')
    with op.batch_alter_table('league_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_purchases_league_id'))

    op.drop_table('league_purchases')
    with op.batch_alter_table('funnel_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funnel_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_funnel_events_league_id'))
        batch_op.drop_index(batch_op.f('ix_funnel_events_event'))

    op.drop_table('funnel_events')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_league_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_league_id'))

    op.drop_table('audit_events')
    op.drop_table('admin_overrides')
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_code'))

    op.drop_table('leagues')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_tournament_id'))

    op.drop_table('fixtures')
    with op.batch_alter_table('coverstory_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverstory_rounds_room_code'))

    op.drop_table('coverstory_rounds')
    op.drop_table('coverstory_playtest_reports')
    op.drop_table('coverstory_player_profiles')
    op.drop_table('coverstory_custom_packs')
    # ### end Alembic commands ###
